//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddonProduccionEnsDes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddonProduccionEnsDes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 008-ALM.
        /// </summary>
        internal static string AlmSalida {
            get {
                return ResourceManager.GetString("AlmSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;frmCfgProIGV&quot; title=&quot;Configuracion Prorrata IGV&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;350&quot; top=&quot;150&quot; width=&quot;270&quot; height=&quot;361&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXD_CFG_PROR&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;actio [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmCfgProIGV {
            get {
                return ResourceManager.GetString("frmCfgProIGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmDesen&quot; title=&quot;EXXIS - Desensamble&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;350&quot; top=&quot;150&quot; width=&quot;1179&quot; height=&quot;427&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXC_DESE&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmDesensamble {
            get {
                return ResourceManager.GetString("frmDesensamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmDesen&quot; title=&quot;EXXIS - Desensamble&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;350&quot; top=&quot;150&quot; width=&quot;1179&quot; height=&quot;427&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXC_DESE&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmDesensamble2 {
            get {
                return ResourceManager.GetString("frmDesensamble2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmEns&quot; title=&quot;EXXIS - Ensamble&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;350&quot; top=&quot;150&quot; width=&quot;1179&quot; height=&quot;427&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXC_ENSA&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;&gt;
        ///     [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmEnsamble {
            get {
                return ResourceManager.GetString("frmEnsamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmFormulacion&quot; title=&quot;EXXIS - Formulación&quot; visible=&quot;1&quot; default_button=&quot;1&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;350&quot; top=&quot;150&quot; width=&quot;1179&quot; height=&quot;443&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;EXP_OFRM&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmFormulacion {
            get {
                return ResourceManager.GetString("frmFormulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;frmDia&quot; title=&quot;Liquidación Prorrata IGV&quot; visible=&quot;0&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;200&quot; top=&quot;100&quot; width=&quot;866&quot; height=&quot;437&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_LIST&quot;&gt;
        ///              &lt;Columns /&gt;
        ///   [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string frmLiqProIGV {
            get {
                return ResourceManager.GetString("frmLiqProIGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconoModulo {
            get {
                object obj = ResourceManager.GetObject("IconoModulo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Application&gt;
        ///	&lt;Menus&gt;
        ///		&lt;action type=&quot;add&quot;&gt;
        ///			&lt;Menu Checked=&quot;0&quot; Enabled=&quot;1&quot; FatherUID=&quot;4352&quot; Position=&quot;98&quot; String=&quot;EXC - Ensamble&quot; Type=&quot;1&quot; UniqueID=&quot;CPRENS&quot;/&gt;
        ///		&lt;/action&gt;
        ///		&lt;action type=&quot;add&quot;&gt;
        ///			&lt;Menu Checked=&quot;0&quot; Enabled=&quot;1&quot; FatherUID=&quot;4352&quot; Position=&quot;99&quot; String=&quot;EXC - Desensamble&quot; Type=&quot;1&quot; UniqueID=&quot;CPRDES&quot;/&gt;
        ///		&lt;/action&gt;
        ///	&lt;/Menus&gt;
        ///&lt;/Application&gt;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXC_PRODED.
        /// </summary>
        internal static string NombreAddon {
            get {
                return ResourceManager.GetString("NombreAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 19.
        /// </summary>
        internal static string TOperacionEntrada {
            get {
                return ResourceManager.GetString("TOperacionEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10.
        /// </summary>
        internal static string TOperacionSalida {
            get {
                return ResourceManager.GetString("TOperacionSalida", resourceCulture);
            }
        }
    }
}
